### ISSUE TITLE
Dragging Plane does not update Note Position

### ISSUE THREAD

**Issue by benjic** [orbitable/bridge#203]
When I drag the plane while the simulation is paused the notes do not follow along. Resuming playback causes the notes to snap back.

**Comment by mkinsey** [comment]
What if we hid the note panel during the drag event? Sounds like a straight forward fix and I think it would make sense visually.

**Comment by benjic** [comment]
@mkinsey We could do something like that in a second pass. That would require setting some drag state and setting up the notes to render based on it. In orbitable/bridge#228 I just flagged the scope as dirty and it causes the note panels to rerender.
