### ISSUE TITLE
Control Buttons are Clipped in Firefox

### ISSUE THREAD

**Issue by benjic** [orbitable/bridge#72]
When viewing the bridge in Firefox the buttons are clipped along the right edge.

**Comment by benjic** [comment]
![1458059277](https://cloud.githubusercontent.com/assets/135916/13785488/6240f358-ea99-11e5-99ae-7149fb54c756.png)

**Comment by aaroncameron21** [comment]
This may be helpful to anyone tackling this, I'll give it a shot soon
http://stackoverflow.com/questions/34087062/bootstrap-button-cut-off-in-firefox
