### ISSUE TITLE
Tooltips (in traditional sense) on buttons

### ISSUE THREAD

**Issue by aaroncameron21** [orbitable/bridge#91]
[Pretty tooltips via Bootstrap](http://v4-alpha.getbootstrap.com/components/tooltips/#example-enable-tooltips-everywhere)

This isn't high priority, but I thought this would be a nice-looking way of hinting at a buttons function, especially for the ones without text labels.

**Comment by benjic** [comment]
@aaroncameron21 had done preliminary stuff here. Maybe he could share what accomplished if relevant at this point.
